# Generated by Django 5.1.5 on 2025-01-25 17:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beDoggo', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='chip_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='phone_emergency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pets/photos/'),
        ),
        migrations.AddField(
            model_name='pet',
            name='sterilized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petaccess',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='petaccess',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='is_veterinarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile_pictures/'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vet_license_number', models.CharField(max_length=50, unique=True)),
                ('clinic_name', models.CharField(blank=True, max_length=100, null=True)),
                ('clinic_address', models.TextField(blank=True, null=True)),
                ('clinic_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('available_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='veterinarian_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('visit_reason', models.CharField(max_length=200)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('medication', models.TextField(blank=True, null=True)),
                ('vaccines', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('test_results', models.TextField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('next_visit', models.DateField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='medical_records/attachments/')),
                ('images', models.ImageField(blank=True, null=True, upload_to='medical_records/images/')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='beDoggo.pet')),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='beDoggo.veterinarian')),
            ],
        ),
    ]
