# Generated by Django 5.1.5 on 2025-01-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beDoggo', '0003_pet_chip_number_pet_color_pet_phone_emergency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='photo',
        ),
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pets/images/'),
        ),
    ]
