# Generated by Django 5.1.5 on 2025-01-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beDoggo', '0006_alter_accesscode_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpsdevice',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='gpsdevice',
            name='uuid',
        ),
        migrations.AddField(
            model_name='gpsdevice',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
