# Generated by Django 5.1.5 on 2025-01-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beDoggo', '0007_remove_gpsdevice_qr_code_remove_gpsdevice_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsdevice',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
