# Generated by Django 5.1.5 on 2025-01-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beDoggo', '0008_alter_gpsdevice_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpsdevice',
            old_name='code',
            new_name='device_code',
        ),
    ]
