# Generated by Django 5.1.5 on 2025-01-29 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beDoggo', '0009_rename_code_gpsdevice_device_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpsdevice',
            old_name='device_code',
            new_name='code',
        ),
    ]
