# Generated by Django 5.1.5 on 2025-01-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beDoggo', '0012_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
