# Generated by Django 5.1.5 on 2025-01-31 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beDoggo', '0013_user_google_token'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
