# Generated by Django 5.1.5 on 2025-01-31 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beDoggo', '0016_alter_medicalrecord_attachments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='google_token',
        ),
    ]
