# Generated by Django 5.1.5 on 2025-02-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beDoggo', '0018_remove_pet_age_pet_birth_date_pet_chip_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='passport',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
